### ISSUE TITLE
Open for contribution

### ISSUE THREAD

**Issue by Siddhant-Jha** [Siddhant-Jha/IP_Tracker#1]
Open for contribution under Hacktoberfest

**Comment by Shivam4747** [comment]
yay! i am ready! I would like to contribute!

**Comment by soulee-dev** [comment]
I'd like to contribute to this repository. What can i help you?

**Comment by Srinjoycode** [comment]
I am adding a readme file to the repo, would you please merge it ?

**Comment by Siddhant-Jha** [comment]
> I'd like to contribute to this repository. What can i help you?

Can you please refactor the code for better readability

**Comment by Siddhant-Jha** [comment]
> yay! i am ready! I would like to contribute!

Looking forward to it

**Comment by snehagupta-4** [comment]
I'd like to contribute in this

**Comment by soulee-dev** [comment]
> > I'd like to contribute to this repository. What can i help you?
> 
> Can you please refactor the code for better readability

Yeah I'll take this job.

**Comment by Siddhant-Jha** [comment]
> I am adding a readme file to the repo, would you please merge it ?

Please add a pull request Srinjoy, Will merge it after reviewing

**Comment by Siddhant-Jha** [comment]
> I'd like to contribute in this

Can you improve readability of result?

**Comment by soulee-dev** [comment]
@Siddhant-Jha Pull Request #5 
Is there anything else I can help you with?

**Comment by Siddhant-Jha** [comment]
> @Siddhant-Jha Pull Request #5 
> Is there anything else I can help you with?

Can you please add test cases?

**Comment by Siddhant-Jha** [comment]
> @Siddhant-Jha Pull Request #5 
> Is there anything else I can help you with?

Thanks for your contribution, I appreciate your efforts.
Will let you know if requirement for your assistance arises

**Comment by abhirambsn** [comment]
I made a pull request which adds some error handling code and converts all the processing into functions for code re-usability, kindly review it

**Comment by Siddhant-Jha** [comment]
> I made a pull request which adds some error handling code and converts all the processing into functions for code re-usability, kindly review it 

Thank you so much for your contribution Abhiram, Give me some time to review the changes and then I will merge the requeste. Hope you understand ✌️

**Comment by soulee-dev** [comment]
> > I made a pull request which adds some error handling code and converts all the processing into functions for code re-usability, kindly review it
> 
> Thank you so much for your contribution Abhiram, Give me some time to review the changes and then I will merge the requeste. Hope you understand ✌️

Could you add "hacktoberfest" topic on your repository?

**Comment by Siddhant-Jha** [comment]
> > > I made a pull request which adds some error handling code and converts all the processing into functions for code re-usability, kindly review it
> > 
> > 
> > Thank you so much for your contribution Abhiram, Give me some time to review the changes and then I will merge the requeste. Hope you understand v
> 
> Could you add "hacktoberfest" topic on your repository?

I have added the Hacktoberfeast as topic
